# The items in the ``sphinx`` list are the name of Sphinx builders
# supported by ``sphinx-build``.

editions:
  - 'shell'
  - 'python'
  - 'csharp'
### --- ####

python-web-base:
  edition: python
  inherit: python-base
  tags:
    - python
    - web
    - website

shell-web-base:
  edition: shell
  inherit: shell-base
  tags:
    - shell
    - web
    - website

csharp-web-base:
  edition: csharp
  inherit: csharp-base
  tags:
    - csharp
    - web
    - website

### --- ####
dirhtml-python:
  builder: dirhtml
  inherit: python-web-base
html-python:
  builder: html
  inherit: python-web-base


dirhtml-shell:
  builder: dirhtml
  inherit: shell-web-base
html-shell:
  builder: html
  inherit: shell-web-base

dirhtml-csharp:
  builder: dirhtml
  inherit: csharp-web-base
html-cpp:
  builder: html
  inherit: csharp-web-base
### --- ####
root-base:
  languages: ['es', 'fr', 'ja', 'it', 'zh']
  tags: ['primer', 'getting-started']
drivers-base:
  inherit: root-base
  tags: 'drivers'
  excluded:
    - /installation.txt
    - /drivers.txt
    - /tutorial/install-mongodb-on-debian.txt
    - /tutorial/install-mongodb-on-linux.txt
    - /tutorial/install-mongodb-on-os-x.txt
    - /tutorial/install-mongodb-on-red-hat.txt
    - /tutorial/install-mongodb-on-ubuntu.txt
    - /tutorial/install-mongodb-on-amazon.txt
    - /tutorial/install-mongodb-on-suse.txt
    - /tutorial/install-mongodb-on-windows.txt
    - /tutorial/install-on-linux.txt
python-base:
  inherit: drivers-base
  edition: python
  excluded: []
shell-base:
  inherit: root-base
  edition: shell
  tags: 'core'
  excluded: []
csharp-base:
  inherit: drivers-base
  edition: csharp
  excluded: []
...
